### ISSUE TITLE
FYDP Advisor Agreement. Due Sept 23 2022

### ISSUE THREAD

**Issue by SammyRobensParadise** [FYDPE/docs#7]
[SYDE461-F2022-01-Project Advisor Agreement Form.pdf](https://github.com/FYDPE/docs/files/9550534/SYDE461-F2022-01-Project.Advisor.Agreement.Form.pdf)

Due September 23rd, 2022. 1% deduction if not completed on time.

**Comment by SammyRobensParadise** [comment]
@JJwilkin the actual agreement form is not that much work, but finding an advisor is a lot more work as it turns out

**Comment by SammyRobensParadise** [comment]
Closing this since @hnagri52 submitted it!

**Comment by hnagri52** [comment]
Thanks for closing @SammyRobensParadise . Adding submission receipt:



![Image](https://user-images.githubusercontent.com/47333088/191351969-8d94291b-692e-436b-8a67-69707031158e.png)
