### ISSUE TITLE
Project Description: Due Sept 23 2022 5%

### ISSUE THREAD

**Issue by SammyRobensParadise** [FYDPE/docs#8]
We need to write a project description document. It is with 5%
Instructions attached

[SYDE461-F2022-02-Project Description.pdf](https://github.com/FYDPE/docs/files/9550520/SYDE461-F2022-02-Project.Description.pdf)

## Subtasks

- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #35

**Comment by hnagri52** [comment]
![Image](https://user-images.githubusercontent.com/47333088/191885992-fdface81-d9c4-498d-9087-b28616c72ba2.png)

**Comment by SammyRobensParadise** [comment]
🎉
